const TOKEN = 'TOKEN';
const IS_FIRST_LAUNCH ='IS_FIRST_LAUNCH';
const VACCINATORS='VACCINATORS';
const SCANNED_VACCINATION='SCANNED_VACCINATION';
const ALL_MEDICINE = 'ALL_MEDICINE';
const LIST_VACCINATION = 'LIST_VACCINATION';

export default {
    TOKEN,
    IS_FIRST_LAUNCH,
    VACCINATORS,
    SCANNED_VACCINATION,
    ALL_MEDICINE,
    LIST_VACCINATION
};